profiles:
  default:
    duration: 4w
    pass_threshold: 51
    periodic_status_check: "2 weeks"
    close_on_passing: true
    allowed_voters:
      teams:
        - oversight-committee-members
  super:
    duration: 4w
    pass_threshold: 66
    periodic_status_check: "2 weeks"
    close_on_passing: true
    allowed_voters:
      teams:
        - oversight-committee-members